#ifndef CUART_LINE_TYPES_H
#define CUART_LINE_TYPES_H

#define CUART_LTYPE_STRAIGHT 0x00
#define CUART_LTYPE_90l 0x01
#define CUART_LTYPE_90r 0x02
#define CUART_LTYPE_tl 0x03
#define CUART_LTYPE_tr 0x04
#define CUART_LTYPE_t 0x05
#define CUART_LTYPE_X 0x06
#define CUART_LTYPE_SPACE 0x07
#define CUART_LTYPE_UNKNOWN 0x20

#endif /* CUART_LINE_TYPES_H */
