#ifndef I2C_ADDRESSES_H
#define I2C_ADDRESSES_H

#define I2C_ADDRESSS_MOTOR_CONTROLLER 0x08
#define I2C_ADDRESS_IO_EXTENDER 0x49
#define I2C_ADDRESS_DISPLAY 0x3c
// #define I2C_ADDRESS_DISPLAY 0x3d

#define I2C_ADDRESS_COMPASS 0x0d
#define I2C_ADDRESS_ACCELEROMETER 0x68
// #define I2C_ADDRESS_ACCELEROMETER 0x69

#endif /* I2C_ADDRESSES_H */
