#ifndef I2C_ADDRESSES_H
#define I2C_ADDRESSES_H

#define I2C_ADDRESSS_MOTOR_CONTROLLER 0x08
#define I2C_ADDRESS_IO_EXTENDER 0x09
#define I2C_ADDRESS_IO_EXT_PCF 0x20
#define I2C_ADDRESS_DISPLAY 0x3c

#define I2C_ADDRESS_COMPASS_BMM 0x13
#define I2C_ADDRESS_COMPASS_HMC 0x1E
#define I2C_ADDRESS_ACCELEROMETER 0x68

#define I2C_ADDRESS_TOF_DEFAULT 0x29
#define I2C_ADDRESS_TOF_CLAW 0x30
#define I2C_ADDRESS_TOF_SIDE 0x31


#endif /* I2C_ADDRESSES_H */
