#ifndef I2C_ADDRESSES_H
#define I2C_ADDRESSES_H

#define I2C_ADDRESSS_MOTOR_CONTROLLER 0x08
#define I2C_ADDRESS_IO_EXTENDER 0x09
#define I2C_ADDRESS_DISPLAY 0x3c
// #define I2C_ADDRESS_DISPLAY 0x3d

// #define I2C_ADDRESS_COMPASS 0x0d
#define I2C_ADDRESS_COMPASS 0x1e
#define I2C_ADDRESS_ACCELEROMETER 0x68
// #define I2C_ADDRESS_ACCELEROMETER 0x69

#define I2C_ADDRESS_TOF_DEFAULT 0x29
#define I2C_ADDRESS_TOF_LEFT 0x2A
#define I2C_ADDRESS_TOF_RIGHT 0x2B
#define I2C_ADDRESS_TOF_BACK 0x2C

#endif /* I2C_ADDRESSES_H */
