#pragma once

#define ROOM_CORNER_POS_TL_X 150
#define ROOM_CORNER_POS_TL_Y 700

#define ROOM_CORNER_POS_TR_X 1000
#define ROOM_CORNER_POS_TR_Y 700

#define ROOM_CORNER_POS_BL_X 150
#define ROOM_CORNER_POS_BL_Y 150

#define ROOM_CORNER_POS_BR_X 1000
#define ROOM_CORNER_POS_BR_Y 150
