#pragma once

#define ANGLE_GREIFER_OPEN 65
#define ANGLE_GREIFER_CLOSE 5
#define ANGLE_GREIFER_CLOSE_CUBE 1
#define ANGLE_GREIFER_AUSRICHTEN 30

#define ANGLE_GREIFER_DOWN 0
#define ANGLE_GREIFER_MID 100
#define ANGLE_GREIFER_UP 180
